// src/App.tsx
import { About } from "./components/About";
import { FAQ } from "./components/FAQ";
import { Features } from "./components/Features";
import { Footer } from "./components/Footer";
import { Hero } from "./components/Hero";
import { Advantages } from "./components/Advantages";
import { Navbar } from "./components/Navbar";
import { ScrollToTop } from "./components/ScrollToTop";
import { Cases } from "./components/Cases";
import { Sponsors } from "./components/Sponsors";
import GoogleAnalytics from "./components/GoogleAnalytics";
import "./App.css";

function App() {
  return (
    <>
      <GoogleAnalytics />
      <Navbar />
      <Hero />
      <Sponsors />
      <Advantages />
      <Features />
      <Cases />
      {/* <Cta /> */}
      {/* <Testimonials /> */}
      {/* <Team /> */}
      {/* <Pricing /> */}
      {/* <Newsletter /> */}
      <FAQ />
      <About />
      <Footer />
      <ScrollToTop />
    </>
  );
}

export default App;

// src/App.vue
<script setup lang="ts">
import Navbar from "./components/Navbar.vue";
import Hero from "./components/Hero.vue";
import Benefits from "./components/Benefits.vue";
import Features from "./components/Features.vue";
import Services from "./components/Services.vue";
import HowItWorks from "./components/HowItWorks.vue";
import Sponsors from "./components/Sponsors.vue";
import Testimonials from "./components/Testimonials.vue";
import Team from "./components/Team.vue";
import Pricing from "./components/Pricing.vue";
import Community from "./components/Community.vue";
import Contact from "./components/Contact.vue";
import FAQ from "./components/FAQ.vue";
import Footer from "./components/Footer.vue";
import Product from "./components/Product.vue";
</script>

<template>
  <Navbar />
  <Hero />
  <Product />
  <Sponsors />
  <Benefits />
  <Features />
  <Services />
  <!-- <HowItWorks /> -->
  <!-- <Testimonials /> -->
  <!-- <Team /> -->
  <!-- <Community /> -->
  <!-- <Pricing /> -->
  <!-- <Contact /> -->
  <!-- <FAQ /> -->
  <Footer />
</template>
